
branches:
  # If you enable "Build pushed branches" in Travis CI settings,
  # all branches will be built
  # This just ensures that at least these are built
  only: [main, master]

language: python
python: ["3.9"]